# Generated by Django 3.1 on 2020-08-26 22:56

from django.db import migrations, models
import file_handler_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=file_handler_app.models.upload_to_unique_folder),
        ),
    ]
