# Generated by Django 3.1 on 2020-08-26 23:55

from django.db import migrations, models
import file_handler_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0002_auto_20200826_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(max_length=255, null=True, storage=file_handler_app.utils.MediaFileSystemStorage(), upload_to=file_handler_app.utils.upload_to_unique_folder),
        ),
    ]
