# Generated by Django 3.1 on 2020-08-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0008_auto_20200828_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='file_name_hash',
            new_name='file_hash',
        ),
    ]
