# Generated by Django 3.1 on 2020-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0010_auto_20200828_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='hash_name',
            field=models.CharField(max_length=256),
        ),
    ]
