# Generated by Django 3.1 on 2020-08-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0011_auto_20200828_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='hash_name',
            field=models.CharField(default='Null', max_length=256, verbose_name='ango.db.models.fields.files.FileField>'),
        ),
    ]
