# Generated by Django 3.1 on 2020-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0012_auto_20200828_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='hash_name',
        ),
    ]
