# Generated by Django 3.1 on 2020-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0013_remove_data_hash_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='hash_name',
            field=models.CharField(default='Null', max_length=256),
        ),
    ]
