# Generated by Django 3.1 on 2020-08-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0016_auto_20200828_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='hash_name',
            new_name='hash',
        ),
    ]
