# Generated by Django 3.1 on 2020-08-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler_app', '0017_auto_20200828_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='hash',
            new_name='file_hash',
        ),
    ]
